### ISSUE TITLE
Unable to connect my client device to AWS greengrass core

### ISSUE THREAD

**Issue by sagark82** [aws/aws-greengrass-core-sdk-python#16] opened 2023-01-16 12:07 UTC
Hi, I am trying to connect 2 laptops on my personal wifi with one laptop serving as AWS greengrass core while another acting as client device. While trying the basic_discovery.py getting socket error as shown below. Kindly help me to identify the cause.
1/ I have setup the policy for both core device and client device as specified in the tutorial

Debug log is also attached

PS E:\AWS Greengrass\certs> python3 "E:\AWS Greengrass\basic_discovery.py" --thing_name myLaptop02 --topic 'clients/myLaptop02/hello/world' --message 'Hello World!' --ca_file AmazonRootCA1.pem --cert device.pem.crt --key private.pem.key --region us-east-1 --verbosity Warn
Performing greengrass discovery...
[ERROR] [2023-01-16T12:10:19Z] [00002308] [socket] - id=000001A2C35B5D20 handle=00000000000004EC: connect completion triggered with error -1073741252
[ERROR] [2023-01-16T12:10:19Z] [00002308] [socket] - id=000001A2C35B5D20 handle=00000000000004EC: connection error with code 1049
Traceback (most recent call last):
[ERROR] [2023-01-16T12:10:20Z] [00002308] [http-connection] - static: Client connection failed with error 1051 (AWS_IO_SOCKET_CLOSED).
  File "E:\AWS Greengrass\basic_discovery.py", line 62, in <module>
    discover_response = resp_future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\awsiot\greengrass_discovery.py", line 103, in on_connection_completed
    connection = conn_future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AWS_IO_SOCKET_CLOSED: socket is closed.

[Debug_Log.txt](https://github.com/aws/aws-greengrass-core-sdk-python/files/10425636/Debug_Log.txt)

**Comment by MikeDombo** [comment] 2023-01-16 21:29
What is the full policy associated with the certificate that you're using?


Did you "associate" the my laptop thing with your Greengrass core device using the client device associate API? https://docs.aws.amazon.com/greengrass/v2/developerguide/associate-client-devices.html

Connection closing would seem to indicate that AWS does not trust the certificate you're providing.


Ensure you follow every single step precisely in this tutorial: https://docs.aws.amazon.com/greengrass/v2/developerguide/client-devices-tutorial.html

**Comment by MikeDombo** [comment] 2023-01-16 21:37
-1073741252 error would appear to mean network unreachable. Is this device behind a proxy or does the network block any ports including 443, 8443, or 8883?

**Comment by MikeDombo** [comment] 2023-01-17 19:14
Please also note that this isn't the right repository. You're using `basic_discovery.py` which should come from https://github.com/aws/aws-iot-device-sdk-python-v2/blob/main/samples/basic_discovery.py

**Comment by sagark82** [comment] 2023-01-23 13:40
Hello @MikeDombo , many thanks for your replies and apologies for delay in my acknowledgement.
1. The client device is attached to the core device as shown in the command output - list_device.txt
2. I have tried to follow all the steps of the tutorial. The policy permissions are also attached for both core (core_device.txt) and client device (client_device.txt)
3. The PoC is being done on home wifi with no proxy
4. I will post the query to the right repo. basic_discovery is the first step but eventually I want to explore all items in the python SDK
[core_device.txt](https://github.com/aws/aws-greengrass-core-sdk-python/files/10480216/core_device.txt)
[client_device.txt](https://github.com/aws/aws-greengrass-core-sdk-python/files/10480217/client_device.txt)
[list_device.txt](https://github.com/aws/aws-greengrass-core-sdk-python/files/10480218/list_device.txt)

**Comment by MikeDombo** [comment] 2023-01-23 14:25
Your device is called `myLaptop02`, but the policy is for `MyLaptop*`. That won't work, the cases are different for `m`.

**Comment by sagark82** [comment] 2023-01-24 14:51
Hello @MikeDombo , this indeed was a silly mistake which I have since corrected and reinstalled the certificate in client device but still no change in outcome. I have one question regarding connectivity. In the debug log, I see that it is trying to connect to 54.xx.xxx.xxx:443 where it is failing. However, the hostname of my core device is 192.xxx.xx.xx. Nowhere in the log I see it trying to connect to any host with ip address 192.xxx.xx.xx. Is this something that needs any action? So essentially, I am trying to ask how does basic_discovery.py know the host information to connect to?

**Comment by MikeDombo** [comment] 2023-01-24 14:53
Please see: https://docs.aws.amazon.com/greengrass/v2/developerguide/manage-core-device-endpoints.html.

You can view the associated endpoint in the console under the core device, then client devices tab. Deploying the IP Detector component with proper permissions will automatically add the local IP.

**Comment by sagark82** [comment] 2023-01-24 15:04
IP Detector is deployed and I can see endpoint for core device is correctly captured in the console. However, when I am trying to run basic_discovery.py from client device thats where the socket_closed error is encountered and I dont see the local endpoint of the core device anywhere in the log.

**Comment by MikeDombo** [comment] 2023-01-24 15:15
What IP addresses do you see in the console?

Please provide logs again. 54 IP is often EC2 which may mean that discovery hasn't even gotten the list of IPs yet.

**Comment by sagark82** [comment] 2023-01-24 15:17
IP address in console is 192.168.1.60, attaching the log again. I have extracted the relevant lines here....

[DEBUG] [2023-01-16T12:08:15Z] [00001014] [socket] - id=000001AAE1C1F0B0 handle=00000000000004D0: beginning connect.
[DEBUG] [2023-01-16T12:08:15Z] [00001014] [socket] - id=000001AAE1C1F0B0 handle=00000000000004D0: connecting to endpoint **54.84.191.149:443**.
[DEBUG] [2023-01-16T12:08:15Z] [00001014] [task-scheduler] - id=000001AAE20362A0: Scheduling (null) task for future execution at time 359502686828400
[ERROR] [2023-01-16T12:08:15Z] [00001014] [socket] - id=000001AAE1C1E860 handle=00000000000004CC: connect completion triggered with error -1073741252
[ERROR] [2023-01-16T12:08:15Z] [00001014] [socket] - id=000001AAE1C1E860 handle=00000000000004CC: connection error with code 1049
[DEBUG] [2023-01-16T12:08:15Z] [00001014] [channel-bootstrap] - id=000001AAE1DFEE60: client connection on socket 000001AAE1C1E860 completed with error 1049.


https://github.com/aws/aws-greengrass-core-sdk-python/files/10425636/Debug_Log.txt

**Comment by MikeDombo** [comment] 2023-01-24 15:19
This log is from days ago. Did you fix the permission problem I pointed out?
You must fix that and run discovery again. Provide logs from that run.


What is the thing name of the Greengrass core device? What is the thing name for the client device? What is the exact command that you are using now?

**Comment by sagark82** [comment] 2023-01-24 15:52
[Debug_Log_2401.txt](https://github.com/aws/aws-greengrass-core-sdk-python/files/10491694/Debug_Log_2401.txt)
Here's the latest log after correcting the policy permission issue.

Core device - GreengrassQuickStartCore-183b29ed40f, local ip - 192.168.1.60
Client device - myLaptop02, local ip - 192.168.1.75

Command used which is resulting in the error shown in debug log.

python3 "E:\AWS Greengrass\basic_discovery.py" --thing_name myLaptop02 --topic 'clients/myLaptop02/hello/world' --message 'Hello World!' --ca_file AmazonRootCA1.pem --cert device.pem.crt --key private.pem.key --region us-east-1 --verbosity Debug

**Comment by MikeDombo** [comment] 2023-01-24 15:57
What is the policy currently attached to the client device certificate? Please make it an allow all policy by using * for action and resource.

**Comment by MikeDombo** [comment] 2023-01-24 16:23
What is happening is that you're still unable to connect to AWS. There isn't any Greengrass involvement yet.
You're failing to connect because the certificate isn't registered, it isn't active, it isn't registered in us-east-1 which is what you're connecting to,  the certificate wasn't created by AWS, or the certificate permissions do not properly allow the IoT connect action.

One of these should be the cause of your problem.

**Comment by sagark82** [comment] 2023-01-24 17:04
Thanks, @MikeDombo , I deleted the client device and created a new one and this time configured a fully permissive policy. It worked, thanks a lot for your help!!!, we can close this

**Closed as completed** 2023-01-24 17:07 UTC
